#!/usr/bin/env ruby

require "schwab_mcp"
require "dotenv/load"

required_vars = [
  'SCHWAB_ACCOUNT_NUMBER',
  'SCHWAB_API_KEY',
  'SCHWAB_APP_SECRET',
  'SCHWAB_CALLBACK_URI',
  'TOKEN_PATH'
]
missing_vars = required_vars.select { |var| ENV[var].nil? || ENV[var].empty? }

unless missing_vars.empty?
  # puts "Missing required environment variables: #{missing_vars.join(', ')}"
  # puts "\nPlease set:"
  # puts "  export SCHWAB_API_KEY='your_api_key'"
  # puts "  export SCHWAB_APP_SECRET='your_app_secret'"
  # puts "  export APP_CALLBACK_URL='https://127.0.0.1'"
  # puts "  export TOKEN_PATH='/path/to/tokens.json'"
  exit 1
end


SchwabMCP::Server.new.start