#!/usr/bin/env ruby

require "schwab_mcp"
require "dotenv/load"

required_vars = [
  'SCHWAB_API_KEY',
  'SCHWAB_APP_SECRET',
  'SCHWAB_CALLBACK_URI',
  'TOKEN_PATH'
]
missing_vars = required_vars.select { |var| ENV[var].nil? || ENV[var].empty? }

unless missing_vars.empty?
  puts "Missing required environment variables: #{missing_vars.join(', ')}"
  exit 1
end

puts "All required environment variables are set."

SchwabMCP::Server.new.start